// <auto-generated />
using DoctorPatient.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorPatient.Migrations
{
    [DbContext(typeof(DoctorPatientContext))]
    [Migration("20240514154337_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DoctorPatient.Models.Doctor", b =>
                {
                    b.Property<int>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocId"), 1L, 1);

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Experience")
                        .HasColumnType("real");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DocId = 1,
                            DocName = "Ram",
                            Experience = 0f,
                            Specialization = "Cardiologist"
                        },
                        new
                        {
                            DocId = 2,
                            DocName = "Raj",
                            Experience = 0f,
                            Specialization = "Orthologist"
                        },
                        new
                        {
                            DocId = 3,
                            DocName = "Rahul",
                            Experience = 0f,
                            Specialization = "Neurologist"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
